### ISSUE TITLE
Auto respawn so no camping, and allow flying in the server settings so people dont get kicked.

### ISSUE THREAD

**Issue by dellman135** [nextinfinity/SuperCraftBros#26] opened 2015-07-27 02:45 UTC

**Comment by ghost** [comment] 2015-07-27 05:50
I haven't joined the game yet, but auto respawning is a must have.

**Comment by justwheel** [comment] 2015-07-27 05:53
Duplicate of #17.

**Comment by nextinfinity** [comment] 2015-07-27 06:23
Auto respawn is a duplicate. Could you please tell me when the player gets kicked for flying? Because in most scenarios this bug is unrelated to the actual kick (shouldn't happen in the first place). The actual server settings are out of my control as the plugin developer.

**Comment by justwheel** [comment] 2015-07-27 16:54
@nextinfinity Players are kicked for flying from NoCheatPlus. In our tests, we played without it enabled, so this is not an issue with the plugin. I believe this ticket should be closed as a duplicate.

**Closed as completed** 2015-07-27 22:58 UTC
Labels: duplicate
